apiVersion: v1
kind: Pod
metadata:
  name: helloWorld
  labels:
    app: helloWorld
spec:
  containers:
  - name: helloworldk8sdemo
    image: cciturria/helloworldk8sdemo
    ports:
    - name: nodejs-port
      containerPort: 3000